// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPySqskHaKIOMNuvAHc78oubXsTmdbRlo',
    appId: '1:995269643045:web:be77ee964b73ac62ee28cc',
    messagingSenderId: '995269643045',
    projectId: 'hobby-65f74',
    authDomain: 'hobby-65f74.firebaseapp.com',
    storageBucket: 'hobby-65f74.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa-Dh7gg39SwZn0uAL3jP6PNj73Xf1DM0',
    appId: '1:995269643045:android:daa9bad34ebc7c47ee28cc',
    messagingSenderId: '995269643045',
    projectId: 'hobby-65f74',
    storageBucket: 'hobby-65f74.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ6limxYw_xBi5CwnTuXCFSG5_SoPFpJM',
    appId: '1:995269643045:ios:59fc9bd924502badee28cc',
    messagingSenderId: '995269643045',
    projectId: 'hobby-65f74',
    storageBucket: 'hobby-65f74.firebasestorage.app',
    iosBundleId: 'com.example.hobby',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ6limxYw_xBi5CwnTuXCFSG5_SoPFpJM',
    appId: '1:995269643045:ios:59fc9bd924502badee28cc',
    messagingSenderId: '995269643045',
    projectId: 'hobby-65f74',
    storageBucket: 'hobby-65f74.firebasestorage.app',
    iosBundleId: 'com.example.hobby',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPySqskHaKIOMNuvAHc78oubXsTmdbRlo',
    appId: '1:995269643045:web:3e952965664965c3ee28cc',
    messagingSenderId: '995269643045',
    projectId: 'hobby-65f74',
    authDomain: 'hobby-65f74.firebaseapp.com',
    storageBucket: 'hobby-65f74.firebasestorage.app',
  );
}
